### ISSUE TITLE
Evohome CC water heater component fails to load

### ISSUE THREAD

**Issue by matthewcky2k** [zxdavb/evohome#23]
Main component loads fine but water heater does not load;

evohome_cc:
  username: redacted
  password: redacted
  scan_interval: 360
  high_precision: true
  use_heuristics: false
  use_schedules: false
  away_temp: 13

Traceback

`2019-01-28 10:17:41 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.water_heater.evohome_cc. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/root/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 117, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.homeassistant/custom_components/water_heater/evohome_cc.py", line 12, in <module>
    from custom_components.evohome_cc import (
ImportError: cannot import name 'EvoBoiler'
2019-01-28 10:17:41 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.evohome_cc.water_heater. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/root/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 117, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.evohome_cc.water_heater'; 'custom_components.evohome_cc' is not a package
2019-01-28 10:17:41 ERROR (MainThread) [homeassistant.loader] Unable to find platform evohome_cc
2019-01-28 10:17:41 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform water_heater.evohome_cc: Platform not found.`

**Comment by zxdavb** [comment]
fixed - closed

**Comment by matthewcky2k** [comment]
humm still fails to load using your latest commit, different error.

`2019-01-30 14:35:43 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.water_heater.evohome_cc. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/root/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 117, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.homeassistant/custom_components/water_heater/evohome_cc.py", line 19, in <module>
    from homeassistant.components.water_heater import (
ImportError: cannot import name 'SUPPORT_ON_OFF'
2019-01-30 14:35:43 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.evohome_cc.water_heater. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/root/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 117, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.evohome_cc.water_heater'; 'custom_components.evohome_cc' is not a package`

**Comment by zxdavb** [comment]
My apologies - using your location, I get: 

```
2019-01-30 15:42:09 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.water_heater.evohome_cc. Make sure all dependencies are installed
Traceback (most recent call last):
   ...
  File "/home/dbonnes/.homeassistant/custom_components/water_heater/evohome_cc.py", line 19, in <module>
    from homeassistant.components.water_heater import (
ImportError: cannot import name 'SUPPORT_ON_OFF'

2019-01-30 15:42:09 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.evohome_cc.water_heater. Make sure all dependencies are installed
Traceback (most recent call last):
   ...
ModuleNotFoundError: No module named 'custom_components.evohome_cc.water_heater'; 'custom_components.evohome_cc' is not a package
```

**Comment by zxdavb** [comment]
OK, now it works - I have:
```
2019-01-30 16:23:37 INFO (MainThread) [custom_components.climate.evohome_cc] setup_platform(): Found Controller, id=123456 (EvoTouch), name=Ql Home (location_idx=0)
   ...
2019-01-30 16:23:37 INFO (MainThread) [custom_components.water_heater.evohome_cc] setup(): Found DHW device, id: 123456 (domesticHotWater)
```
