### ISSUE TITLE
0.52.0: ramses_cc evohome test fails

### ISSUE THREAD

**Issue by silverailscolo** [zxdavb/evohome#317]
Although all ramses_rf tests pass fine in master, one evohome test `tests/tests_old/test_evo_control.py` in ramses_cc involving zones systematically fails when ramses_rf@0.52.0 is set as dependency.
~No clue ATM, investigating.~ ~Working on it~
So `test_evo_control` passes with ramses_rf 0.52.3 as dependency.

But __WITH the ramses_cc option 'Use SQL MessageIndex' switched ON__, evohome users report Zones not being found.

**Comment by silverailscolo** [comment]
Fixed in 0.52.1, but one ramses_cc evohome test won't pass with the SQLite msg_db turned on (default is Off).
Urgent to follow up before next release, but that piece of the code is complex. Help welcome.

**Comment by peternash** [comment]
@silverailscolo - I saw that 0.52.1 was available as pre-release so I installed it via
```
action: update.install
target:
  entity_id: update.ramses_cc_update
data:
  version: 0.52.1
```

All seems OK so far with the default `Use SQLite MessageIndex: off`

I will have some more time later today to see what happens if I turn that on for my Evohome system

**Comment by silverailscolo** [comment]
Thanks.
If you turn on debug logging from the integration page before you switch, we can collect more details. From the test I expect Zones and binary sensors to behave. Sensors and DHW + their values came up empty.

**Comment by peternash** [comment]
@silverailscolo - I've tried switching on `Use SQLite MessageIndex` and here are my initial findings:

- Heating zone (RAD) devices and DHW device show `unknown` status so no UI controls available for either.
- `window_open` sensors for each _zone_ show `unknown` but the `heat_demand` sensors for each _zone_ are showing correctly and updating.
- Zone names are showing correctly
- Evohome controller device is showing OK
- For each radiator valve (TRV) device I'm seeing `battery`, `heat_demand`, `temperature` and `window_open` sensors correctly (note that is `window_open` for the individual TRV devices, not the zone).
- The DHW sensor device (DHW) is showing `temperature` and `battery` correctly
- Using the `ramses_cc.set_zone_mode` action on a zone (RAD) device works OK and changes the mode, setpoint etc even though the device shows `unknown` in the UI
- All OTB sensors look OK

I've attached the first few minutes on log data.  Note that the error:
```
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/protocol.py", line 223, in send_cmd
    raise exc.ProtocolError("The Protocol is currently read-only/paused")
ramses_tx.exceptions.ProtocolError: The Protocol is currently read-only/paused
```
near the start is normal (for me) - I've seen that on startup for a long time, as is the `The config schema is not minimal` message

[home-assistant.log.sav.zip](https://github.com/user-attachments/files/23058202/home-assistant.log.sav.zip)

Controller and some zones:

<img width="509" height="302" alt="Image" src="https://github.com/user-attachments/assets/09a7d22f-754e-4fa1-9ba5-b96c1efae013" />


Zone heat demand:

<img width="523" height="303" alt="Image" src="https://github.com/user-attachments/assets/bd856939-7904-445a-88b5-e1786d66a760" />


Zone window open sensors:

<img width="523" height="303" alt="Image" src="https://github.com/user-attachments/assets/76ac3c84-16ce-4374-9f7d-45cbab4df7ea" />


TRV sensors:

<img width="489" height="215" alt="Image" src="https://github.com/user-attachments/assets/33fbe3f2-d044-4574-b68e-f9705428a07f" />


DHW sensor:

<img width="500" height="188" alt="Image" src="https://github.com/user-attachments/assets/0e71a094-8f29-4a9b-aada-8f6c03cfde56" />

**Comment by peternash** [comment]
@silverailscolo - here's the debug log that includes the Config - the previous attachment was taken from home-assistant.log:

[home-assistant_ramses_cc_2025-10-22T16-53-46.023Z.log](https://github.com/user-attachments/files/23058649/home-assistant_ramses_cc_2025-10-22T16-53-46.023Z.log)

**Comment by silverailscolo** [comment]
@peternash thanks for your logs.
A new ramses_rf release 0.52.2 is just out, with some more details in the logs and 1 change to the code.

Could you set that as ~dependency~ requirement in ramses_cc `manifest.json`, restart and flip the SQL option switch once more?

**Comment by peternash** [comment]
@silverailscolo - I've tested with ramses_rf 0.52.2 and the behaviour seems the same as before - Zone (RAD) and DHW devices `unavailable` but TRV, DHW sensor and OTB devices show OK. Zone names are also OK.  I've attached a debug log for the first few minutes after flipping the SQL option.

[home-assistant_ramses_cc_2025-10-27T07-52-02.705Z.log](https://github.com/user-attachments/files/23159355/home-assistant_ramses_cc_2025-10-27T07-52-02.705Z.log)

**Comment by silverailscolo** [comment]
@peternash Thanks. Would you know the (expected/normal) device IDs for the missing Zone (RAD) and DHW devices?
I expect it is their extended id with suffix that makes their message lookup fail.

**Comment by peternash** [comment]
@silverailscolo - do you mean the entity_id of the devices?  The zones (RAD) devices all have entity_id's like this `climate.01_216136_01`. The last two digits seem to be the Hex representation of the zone number, from `00` to `0b` [correct, eb].
The Stored HW (DHW) device entity_id is `water_heater.01_216136_hw`.  Is that what you were looking for? [Yes, thanks. eb]

**Comment by silverailscolo** [comment]
These seem to be the "extended" device_ids from your log:
```
ramses_cc.broker] Setting up device: 18:072981
ramses_cc.broker] Setting up device: 01:216136
ramses_cc.broker] Setting up device: 01:216136_00
ramses_cc.broker] Setting up device: 01:216136_01
ramses_cc.broker] Setting up device: 01:216136_02
ramses_cc.broker] Setting up device: 01:216136_03
ramses_cc.broker] Setting up device: 01:216136_04
ramses_cc.broker] Setting up device: 01:216136_05
ramses_cc.broker] Setting up device: 01:216136_06
ramses_cc.broker] Setting up device: 01:216136_07
ramses_cc.broker] Setting up device: 01:216136_08
ramses_cc.broker] Setting up device: 01:216136_09
ramses_cc.broker] Setting up device: 01:216136_0A
ramses_cc.broker] Setting up device: 01:216136_0B
ramses_cc.broker] Setting up device: 01:216136_HW
```

Then these binary sensors are created:
```
ramses_cc.broker] Platform setup completed for binary_sensor
ramses_cc.binary_sensor] Found 10:064873: ch_active
ramses_cc.binary_sensor] Found 10:064873: ch_enabled
ramses_cc.binary_sensor] Found 10:064873: cooling_active
...
ramses_cc.binary_sensor] Found 10:064873: fault_present
ramses_cc.binary_sensor] Found 10:064873: bit_2_4
ramses_cc.binary_sensor] Found 10:064873: bit_2_5
ramses_cc.binary_sensor] Found 10:064873: bit_2_6
...
```
Next are the sensors:
```
ramses_cc.broker] Registering platform sensor
ramses_cc.broker] Connecting signal for platform sensor: ra
ramses_cc.broker] Platform setup completed for sensor
ramses_cc.sensor] Found 10:064873: heat_demand
ramses_cc.sensor] Found 10:064873: boiler_output_temp
...
ramses_cc.sensor] Found 10:064873: oem_code
ramses_cc.sensor] Found 10:064873: percent
ramses_cc.sensor] Found 10:064873: value
ramses_cc.sensor] Found 07:050121: temperature
ramses_cc.sensor] Found 13:042605: relay_demand
...
```
The `07:` device seems to be DHW:
```
'dhw_sensor', 'FA', '07:050121', 'B0', '0000', 'FFFF7000')} to gwy.msg_db
2025-10-27 07:48:02.927 INFO (MainThread) [ramses_rf.dispatcher] ||  18:072981 |  10:064873 | RQ | opentherm_msg    |  1C  || {'msg_id': 28, 'msg_type': 'Read-Data', 'msg_name': 'ReturnWaterTemperature', 'description': 'Return water temperature'}
```
Once the msg_db index is created, the Zone is created and 'promoted':
```
[ramses_rf.system.zones] Creating a Zone: 01:216136_02 (<class 'ramses_rf.system.zones.Zone'>)
[ramses_rf.system.schedule] Schedule(zon=01:216136_02 (None)).__init__()
[ramses_rf.system.zones] Promoted a Zone: 01:216136_02 (<class 'ramses_rf.system.zones.RadZone'>)
```

**Comment by peternash** [comment]
Here are my devices:
```
    18:072981: { class: HGI } # SSM-D2 radio
    01:216136: # Evohome controller
    10:064873: # R8810A OTH interface
    13:042605: # BDR91 DHW relay
    07:050121: # Evohome DHW sensor
    22:012299: # DT4R (square)
    34:058721: # Y87RF (round)
```
All the TRV's start with `04:`

The only devices that are `unavailable` are the ones from the first block with names like `01:216136_xx` so as you say, the `_xx`suffix may be the cause.

**Comment by silverailscolo** [comment]
To fetch the value, in `zones.py` a Zone calls:
```
    def _msg_value(self, *args: Any, **kwargs: Any) -> Any:
        return super()._msg_value(*args, **kwargs, zone_idx=self.idx)
```
- [x] check that extra zone_idx= is picked up correctly for e.g. Zone `01:216136_02`.

**Comment by silverailscolo** [comment]
@peternash Made some changes to the new queries to accommodate the DHW special patterns. Could you set current master as dependency and confirm DHW has improved?
In `manifest.json` set: 
"ramses_rf@git+https://github.com/ramses-rf/ramses_rf.git@master"

**Comment by peternash** [comment]
@silverailscolo - I've tested with the modified `manifest.json` as above and no change I'm afraid, DHW device and Zone devices still `unavailable`.  Log attached.

[home-assistant_ramses_cc_2025-10-29T05-53-57.005Z.log](https://github.com/user-attachments/files/23202375/home-assistant_ramses_cc_2025-10-29T05-53-57.005Z.log)

**Comment by silverailscolo** [comment]
From this evohome_test schema I conclude we are still missing the associated sensor, hotwater_valve and actuators (list), correct?

![image](https://github.com/user-attachments/assets/0e2fac1b-909d-4bc4-851d-b42394623feb)

**Comment by Tchirana** [comment]
Hey I can also help in here with more data. Recently switched one of my THM to the new dt4r and needed to contact resideo because I could nit bind it to the evohome. Resideo sayd they released new fw version of controller and any dt4r with date over 2550 uses ramses 3. The new fw comes with a option in advanced settings > system settings to enable legacy ramses 2. I wanted to get rid of the old thm from the integration so i deleted the ramsescc from .storage and deleted and readded the config in the integration. Now i do not see anymore the zones created. I use a mix of HR80, HR92 snd DT92 and DT4R with a 3000 controller with ramses_esp ftom idalo on mqtt

**Comment by peternash** [comment]
@silverailscolo - no, the DHW sensor `07:050121` is available and showing the correct temperature which was also the case on the 0.52.2 ramses_rf, HA entity_id is `sensor.07_050121_temperature`.

It's only the DHW water heater device that's unavailable, it's the device with HA entity_id `water_heater.01_216136_hw`.  Also the zones are `unavailable`, entity_id's `climate.01_216136_00` through `climate.01_216136_0b`


```
friendly_name: Evohome controller System status
id: "01:216136"
working_schema:
  system:
    appliance_control: "10:064873"
  orphans: []
  stored_hotwater:
    sensor: "07:050121"
    hotwater_valve: "13:042605"
    heating_valve: null
  underfloor_heating: {}
  zones:
```

**Comment by Tchirana** [comment]
Switched to 0.52.1 and zones are still not setup. @silverailscolo do you want me to open a separate issue?

**Comment by silverailscolo** [comment]
> Switched to 0.52.1 and zones are still not setup

~No, please keep this as the evohome issue we are working on.~

When you mention 0.52.1 I assume that's ramses_cc pre-release in HACS. Or how did you "switch"?

Please move your previous comment above to a _new_ issue in ramses_cc.
The info from Resideo deserves a place there. If that legacy option is set in hardware, add it to the Wiki instead.
And pls fix your spelling.

**Comment by Tchirana** [comment]
> > Switched to 0.52.1 and zones are still not setup
> 
> No, please keep this as the evohome issue we are working on.
> 
> When you mention 0.52.1 I assume that's ramses_cc pre-release in HACS. Or how did you "switch"?

Yes, i ment the pre-release. Switched by redownload option

**Comment by peternash** [comment]
Just some clarification from me - I'm not seeing any problems with Zones appearing in either Ramses RF 0.51.9-1 or 0.52.1 (note that 0.59.1 _did_ have problems).

I'm only seeing issues when turning on the new `Use SQLite MessageIndex` option in 0.52.1.

**Comment by silverailscolo** [comment]
> It's only the DHW water heater device that's unavailable, it's the device with HA entity_id water_heater.01_216136_hw

@peternash Strange, as the ramses_cc tests can access that information:
```
heater: WaterHeaterEntity = [e for e in water_heaters if e.entity_id == id][0]
    assert heater.unique_id == f"{CTL_ID}_HW"

    assert heater.extra_state_attributes["mode"] == {
        "mode": "temporary_override",
        "active": True,
        "until": "2022-02-10T22:00:00",
    }
```

It might be how it's transferred to HA that's broken.

**Comment by Tchirana** [comment]
@peternash see my post in the main :
https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/4816
I switched to a new THM and was forced to have resideo update the fw on my controller because the new DT4R only works with ramses vers 3. I also wanted to get rid of the old ghost THM so I deleted the ramses_cc from .storage and re-setup the integration. Maybe I should just remove the integration completly from HACS , delete everything related from .storage and retry.

**Comment by Tchirana** [comment]
Ok, i reset everything. Let's see. I still have a backup at hand from when the zones were there

**Comment by silverailscolo** [comment]
@peternash In your most recent log, there is:
```
2025-10-29 05:51:01.481 DEBUG (MainThread) [custom_components.ramses_cc.broker] Registering platform water_heater
2025-10-29 05:51:01.481 DEBUG (MainThread) [custom_components.ramses_cc.broker] Connecting signal for platform water_heater: ramses_cc_new_devices_water_heater
2025-10-29 05:51:01.481 DEBUG (MainThread) [custom_components.ramses_cc.broker] Platform setup completed for water_heater
2025-10-29 05:51:01.481 INFO (MainThread) [custom_components.ramses_cc.water_heater] Found DHW 01:216136_HW
```
So that missing device is created. Finding out what happens next...

**Comment by Tchirana** [comment]
> Ok, i reset everything. Let's see. I still have a backup at hand from when the zones were there

hmmmm, status of the controller remains Unavailable and the zones (RAD) are not created....

**Comment by peternash** [comment]
@Tchirana - sounds like you have a different issue, possibly related to the different firmware on your Evohome controller you mentioned in the [forum](https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/4816)  This issue is specifically looking at using the new `Use SQLite MessageIndex` option.  I would suggest reverting to a backup for now as the new Evohome firmware you mention is a bit of an unknown.

**Comment by Tchirana** [comment]
10-4

**Comment by Tchirana** [comment]
ok reverted to backup and my zones are back.
here are some startup logs :

[logs_debug_29_10_after_revert.log](https://github.com/user-attachments/files/23213600/logs_debug_29_10_after_revert.log)

I am on 0.52.1 , with qos enabled and data from mqtt

**Comment by silverailscolo** [comment]
> So that missing device is created. Finding out what happens next...

From the details in `entity_base` `_delete_msg()` I deduct that:
- a zone/dhw has the ctl (parent's) messages available
- a Ctl has its parents Children's (Zones/dhw) messages available

So:
- [ ] In addition to receiving its own 01:123456_hw (=ctx) messages, adjust the sql qry to include src=self.ctl (if set)

- [ ] For the 10:xxx controller, also fetch its children: adjust the sql qry to include src=self.ctl.dhw and src= self.ctl.zones

**Comment by JeroenTogt** [comment]
Hi having Evohome  with 3 zones and one FAN.

When I switch on the sqlite option the state of the climate state loses some of the settings  ( 44 to 34 items) and also the current temperature goes to null

see 

<img width="579" height="610" alt="Image" src="https://github.com/user-attachments/assets/bb9c0d81-6d58-4001-8875-a987df61aa67" />

and where it is disappeared

<img width="574" height="542" alt="Image" src="https://github.com/user-attachments/assets/780f398b-296a-4142-91c5-c68a841da560" />

Here the state before sqlite

<img width="857" height="816" alt="Image" src="https://github.com/user-attachments/assets/cda87fa4-fdea-40da-89a6-c32f7ab07f9b" />

<img width="756" height="667" alt="Image" src="https://github.com/user-attachments/assets/6839d365-561a-4c31-aca1-40ec9082e56f" />

And here after

<img width="813" height="679" alt="Image" src="https://github.com/user-attachments/assets/93d229a2-ae1a-4eaf-bf6b-c03f265e0226" />

<img width="803" height="490" alt="Image" src="https://github.com/user-attachments/assets/fc041e26-b580-4187-8919-1045ba730818" />

Also attached the log when switched on sqlite. hope this helpes.

[home-assistant_ramses_cc_2025-11-02T13-02-27.246Z.log](https://github.com/user-attachments/files/23291706/home-assistant_ramses_cc_2025-11-02T13-02-27.246Z.log)

here schema

```
"01:007149":
  system:
    appliance_control: "10:057706"
  zones:
    "00":
      actuators:
        - "04:221387"
        - "04:221379"
        - "04:204425"
        - "04:204423"
        - "04:221381"
        - "04:204407"
      sensor: "34:094171"
    "01":
      actuators:
        - "04:204421"
        - "04:221385"
      sensor: "34:195026"
    "02":
      sensor: "34:094165"
orphans_hvac:
  - "37:012161"
  - "37:252531"
```

and know device id's

```
"01:007149":
  class: controller
"04:204407":
  class: radiator_valve
"04:204421":
  class: radiator_valve
"04:204423":
  class: radiator_valve
"04:204425":
  class: radiator_valve
"04:221379":
  class: radiator_valve
"04:221381":
  class: radiator_valve
"04:221385":
  class: radiator_valve
"04:221387":
  class: radiator_valve
"10:057706":
  class: opentherm_bridge
"18:172464":
  class: HGI
"34:094165":
  class: thermostat
"34:094171":
  class: thermostat
"34:195026":
  class: thermostat
"37:012161":
  _note: based upon RFT-N Auto with itho cve-s eco
  class: REM
  commands:
    10Min_Hoog: " I --- 37:012161 37:252531 --:------ 22F3 003 00000A"
    20Min_Hoog: " I --- 37:012161 37:252531 --:------ 22F3 003 000014"
    30Min_Hoog: " I --- 37:012161 37:252531 --:------ 22F3 003 00001E"
    Auto_Mode: " I --- 37:012161 37:252531 --:------ 22F1 003 000304"
    Hoog_Stand: " I --- 37:012161 37:252531 --:------ 22F1 003 000404"
    Laag_Stand: " I --- 37:012161 37:252531 --:------ 22F1 003 000204"
  faked: true
"37:252531":
  _note: Itho CVE-S ECO
  class: FAN
```

**Comment by Tchirana** [comment]
@silverailscolo @peternash i am using the latest of the integration with sqlindex and log_mqtt. Even if I have some issue related to RF3 which is not the scope of this , I see this in the logs of HA and it might be related to this issue:

```
2025-11-02 20:04:08.245 INFO (MainThread) [ramses_rf.dispatcher] ||  04:153231 |  01:226586 |  I | setpoint         |  08  || {'zone_idx': '08', 'setpoint': 5.0}
2025-11-02 20:04:08.248 DEBUG (MainThread) [ramses_rf.database] Old msg replaced: ||  04:153231 |  01:226586 |  I | setpoint         |  08  || {'zone_idx': '08', 'setpoint': 5.0}
2025-11-02 20:04:08.250 DEBUG (MainThread) [ramses_rf.entity_base] For 04:153231 (z_id 04:153231) add msg ||  04:153231 |  01:226586 |  I | setpoint         |  08  || {'zone_idx': '08', 'setpoint': 5.0}, src 04:153231 (TRV): 0.0, dst 01:226586 (CTL) to msg_db.
2025-11-02 20:04:08.255 DEBUG (MainThread) [ramses_rf.database] Overwrote dtm (2025-11-02 20:04:08.234871) for 2309| I|04:153231|08:  I --- 04:153231 --:------ 01:226586 2309 003 0801F4 (contrived log?)
2025-11-02 20:04:14.244 INFO (MainThread) [ramses_rf.dispatcher] ||  04:115445 |  01:226586 |  I | setpoint         |  03  || {'zone_idx': '03', 'setpoint': 21.5}
2025-11-02 20:04:14.247 DEBUG (MainThread) [ramses_rf.database] Old msg replaced: ||  04:115445 |  01:226586 |  I | setpoint         |  03  || {'zone_idx': '03', 'setpoint': 20.0}
2025-11-02 20:04:14.248 DEBUG (MainThread) [ramses_rf.entity_base] For 04:115445 (z_id 04:115445) add msg ||  04:115445 |  01:226586 |  I | setpoint         |  03  || {'zone_idx': '03', 'setpoint': 21.5}, src 04:115445 (TRV): 0.0, dst 01:226586 (CTL) to msg_db.
2025-11-02 20:04:14.253 DEBUG (MainThread) [ramses_rf.database] Overwrote dtm (2025-11-02 20:04:14.231901) for 2309| I|04:115445|03:  I --- 04:115445 --:------ 01:226586 2309 003 030866 (contrived log?)
2025-11-02 20:04:15.742 INFO (MainThread) [ramses_rf.dispatcher] ||  04:153231 |  01:226586 |  I | heat_demand      |  08  || {'zone_idx': '08', 'heat_demand': 0.0}
2025-11-02 20:04:15.745 DEBUG (MainThread) [ramses_rf.database] Old msg replaced: ||  04:153231 |  01:226586 |  I | heat_demand      |  08  || {'zone_idx': '08', 'heat_demand': 0.0}
2025-11-02 20:04:15.746 DEBUG (MainThread) [ramses_rf.entity_base] For 04:153231 (z_id 04:153231) add msg ||  04:153231 |  01:226586 |  I | heat_demand      |  08  || {'zone_idx': '08', 'heat_demand': 0.0}, src 04:153231 (TRV): 0.0, dst 01:226586 (CTL) to msg_db.
2025-11-02 20:04:15.750 DEBUG (MainThread) [ramses_rf.database] Overwrote dtm (2025-11-02 20:04:15.732138) for 3150| I|04:153231|08:  I --- 04:153231 --:------ 01:226586 3150 002 0800 (contrived log?)
2025-11-02 20:04:37.750 INFO (MainThread) [ramses_rf.dispatcher] ||  04:153236 |  01:226586 |  I | heat_demand      |  07  || {'zone_idx': '07', 'heat_demand': 0.44}
2025-11-02 20:04:37.753 DEBUG (MainThread) [ramses_rf.database] Old msg replaced: ||  04:153236 |  01:226586 |  I | heat_demand      |  07  || {'zone_idx': '07', 'heat_demand': 0.44}
2025-11-02 20:04:37.753 DEBUG (MainThread) [ramses_rf.entity_base] For 04:153236 (z_id 04:153236) add msg ||  04:153236 |  01:226586 |  I | heat_demand      |  07  || {'zone_idx': '07', 'heat_demand': 0.44}, src 04:153236 (TRV): 0.44, dst 01:226586 (CTL) to msg_db.
2025-11-02 20:04:37.759 DEBUG (MainThread) [ramses_rf.database] Overwrote dtm (2025-11-02 20:04:37.732143) for 3150| I|04:153236|07:  I --- 04:153236 --:------ 01:226586 3150 002 0758 (contrived log?)
2025-11-02 20:04:42.699 INFO (MainThread) [ramses_rf.dispatcher] ||  04:120170 |  01:226586 |  I | heat_demand      |  04  || {'zone_idx': '04', 'heat_demand': 0.0}
2025-11-02 20:04:42.702 DEBUG (MainThread) [ramses_rf.database] Old msg replaced: ||  04:120170 |  01:226586 |  I | heat_demand      |  04  || {'zone_idx': '04', 'heat_demand': 0.0}
2025-11-02 20:04:42.703 DEBUG (MainThread) [ramses_rf.entity_base] For 04:120170 (z_id 04:120170) add msg ||  04:120170 |  01:226586 |  I | heat_demand      |  04  || {'zone_idx': '04', 'heat_demand': 0.0}, src 04:120170 (TRV): 0.0, dst 01:226586 (CTL) to msg_db.
2025-11-02 20:04:42.708 DEBUG (MainThread) [ramses_rf.database] Overwrote dtm (2025-11-02 20:04:42.689682) for 3150| I|04:120170|04:  I --- 04:120170 --:------ 01:226586 3150 002 0400 (contrived log?)
```
I do not see zones created either but .... I do not see zones created even if I disable sqlindex so my setup might not be concludent.
Hope it helps. If you need more logs, dumps or test just whistle.

**Comment by Tchirana** [comment]
But look what happens if I manually define a zone in the schema like this:

```
"01:226586":
  system:
    appliance_control: "13:187431"
  zones:
    "05":
      _name: Living
      actuators:
        - "04:116909" #HR80
        - "00:031413" #HR80
      class: radiator_valve
      sensor: "22:014440" #new DT4R THM
```

logs:

```
2025-11-02 20:36:38.171 DEBUG (MainThread) [ramses_rf.system.zones] Creating a Zone: 01:226586_05 (<class 'ramses_rf.system.zones.Zone'>)
2025-11-02 20:36:38.172 DEBUG (MainThread) [ramses_rf.system.zones] Promoted a Zone: 01:226586_05 (<class 'ramses_rf.system.zones.RadZone'>)
2025-11-02 20:36:38.428 DEBUG (MainThread) [ramses_rf.entity_base] For 01:226586_05 (z_id 01:226586) add msg ||  01:226586 |            |  I | setpoint         | [..] || [{'zone_idx': '00', 'setpoint': 5.0}, {'zone_idx': '01', 'setpoint': 20.5}, {'zone_idx': '02', 'setpoint': 21.0}, {'zone_idx': '03', 'setpoint': 21.5}, {'zone_idx': '04', 'setpoint': 19.5}, {'zone_idx': '05', 'setpoint': 21.0}, {'zone_idx': '06', 'setpoint': 19.0}, {'zone_idx': '07', 'setpoint': 19.0}, {'zone_idx': '08', 'setpoint': 5.0}], src 01:226586 (CTL), dst 01:226586 (CTL) to msg_db.
2025-11-02 20:36:38.433 DEBUG (MainThread) [ramses_rf.entity_base] For 01:226586_05 (z_id 01:226586) add msg ||  01:226586 |            |  I | temperature      | [..] || [{'zone_idx': '00', 'temperature': 20.57}, {'zone_idx': '01', 'temperature': 19.79}, {'zone_idx': '02', 'temperature': 22.02}, {'zone_idx': '03', 'temperature': 21.6}, {'zone_idx': '05', 'temperature': 22.3}, {'zone_idx': '06', 'temperature': 21.8}, {'zone_idx': '07', 'temperature': 22.1}, {'zone_idx': '08', 'temperature': 19.66}], src 01:226586 (CTL), dst 01:226586 (CTL) to msg_db.
2025-11-02 20:36:38.453 INFO (MainThread) [custom_components.ramses_cc.broker] CHILD THM via_device SET to 01:226586_05 (RAD)
2025-11-02 20:36:38.460 INFO (MainThread) [custom_components.ramses_cc.broker] CHILD TRV via_device SET to 01:226586_05 (RAD)
2025-11-02 20:36:38.465 INFO (MainThread) [custom_components.ramses_cc.broker] CHILD TRV via_device SET to 01:226586_05 (RAD)
2025-11-02 20:36:38.473 DEBUG (MainThread) [custom_components.ramses_cc.broker] Setting up device: 01:226586_05
2025-11-02 20:36:38.489 INFO (MainThread) [custom_components.ramses_cc.binary_sensor] Found 01:226586_05: window_open
2025-11-02 20:36:38.522 INFO (MainThread) [custom_components.ramses_cc.sensor] Found 01:226586_05: heat_demand
2025-11-02 20:36:38.549 INFO (MainThread) [custom_components.ramses_cc.climate] Found zone 01:226586_05
2025-11-02 20:37:38.635 INFO (MainThread) [custom_components.ramses_cc.broker] CHILD THM via_device SET to 01:226586_05 (RAD)
2025-11-02 20:37:38.638 INFO (MainThread) [custom_components.ramses_cc.broker] CHILD TRV via_device SET to 01:226586_05 (RAD)
2025-11-02 20:37:38.641 INFO (MainThread) [custom_components.ramses_cc.broker] CHILD TRV via_device SET to 01:226586_05 (RAD)
2025-11-02 20:38:38.629 INFO (MainThread) [custom_components.ramses_cc.broker] CHILD THM via_device SET to 01:226586_05 (RAD)
2025-11-02 20:38:38.630 INFO (MainThread) [custom_components.ramses_cc.broker] CHILD TRV via_device SET to 01:226586_05 (RAD)
2025-11-02 20:38:38.631 INFO (MainThread) [custom_components.ramses_cc.broker] CHILD TRV via_device SET to 01:226586_05 (RAD)
```

and it actually wants to set the override temp if i do it via HA control:

```
2025-11-02 20:42:48.901 INFO (MainThread) [ramses_rf.dispatcher] ||  18:109940 |  01:226586 |  W | zone_mode        |  05  || {'zone_idx': '05', 'mode': 'advanced_override', 'setpoint': 30.5}
2025-11-02 20:42:48.905 DEBUG (MainThread) [ramses_rf.database] Old msg replaced: ||  18:109940 |  01:226586 |  W | zone_mode        |  05  || {'zone_idx': '05', 'mode': 'advanced_override', 'setpoint': 27.5}
2025-11-02 20:42:48.905 DEBUG (MainThread) [ramses_rf.entity_base] For 18:109940 (z_id 18:109940) add msg ||  18:109940 |  01:226586 |  W | zone_mode        |  05  || {'zone_idx': '05', 'mode': 'advanced_override', 'setpoint': 30.5}, src 18:109940 (HGI), dst 01:226586 (CTL) to msg_db.
2025-11-02 20:42:48.908 DEBUG (MainThread) [ramses_rf.database] Overwrote dtm (2025-11-02 20:42:48.894897) for 2349| W|01:226586|05:  W --- 18:109940 01:226586 --:------ 2349 007 050BEA01FFFFFF (contrived log?)
```

**Comment by silverailscolo** [comment]
> look what happens if I manually define a zone in the schema

Thanks for the experiment. It tells me that the current problem is indeed the association of zones with a controller. Manually adding the zone to the schema makes them show up. That should - and used to - happen automatically as children of a controller.
Won't have time to code coming week, but together with the other user reports it provides enough new ideas.

**Comment by Tchirana** [comment]
> > look what happens if I manually define a zone in the schema
> 
> Thanks for the experiment. It tells me that the current problem is indeed the association of zones with a controller. Adding the manually to the schema makes them show up. That should - and used to - happen automatically as children of a controller. Won't have time to code coming week, but together with the other user reports it provides enough new ideas.

Yes they used to show up but on my side there are two issues:

1. the rf3 protocol
2. the SQlite MessageIndex

Even if the zone shows up now it does not get its name as it is configured on the controller (as it was happening without SQL) and also no controls are active, cannot set temps or overrides.

**Comment by silverailscolo** [comment]
@peternash With latest 0.52.4, would you mind creating another test log with `Use SQLite MessageIndex` turned On?

Note the logging change in HA since 2025.11 and my suggestion to reenable it as mentioned in the ramses_cc [release note](https://github.com/ramses-rf/ramses_cc/releases).

**Comment by peternash** [comment]
@silverailscolo   Looks much better with 0.52.4.  Initially I just enabled `Use SQLite MessageIndex` with debug logging (see attached).  The DHW and all the zones looked OK except that `current temperature` was not showing for 10 of the 12 zones.  All the TRV and OTB sensors looked OK.  After about 10 minutes the `current temperature` was still not showing for 10 of the 12 zones.

I then cleared both caches (second log file) and after a few seconds the DHW and all but one zone came back with the correct names and both current and target temperatures.  One zone is still showing "unavailable" after 10 minuted although it has the correct zone name.  The OTB and TRV sensors appear to be slowly populating which is normal after clearing the cache.

I'll leave it running like this for a while and then try a reboot to see if I can get the remaining zone to show as `available`.

Debug log after enabling `Use SQLite MessageIndex`:

[home-assistant_ramses_cc_2025-12-06T15-38-14.684Z.log](https://github.com/user-attachments/files/23989165/home-assistant_ramses_cc_2025-12-06T15-38-14.684Z.log)

Debug log after clearing both caches with `Use SQLite MessageIndex` enabled:

[home-assistant_ramses_cc_2025-12-06T15-55-55.969Z.log](https://github.com/user-attachments/files/23989168/home-assistant_ramses_cc_2025-12-06T15-55-55.969Z.log)

**Comment by peternash** [comment]
@silverailscolo - a reboot didn't bring the `unavailable` zone back but then I tried just changing the setpoint in the UI and that seemed to do the trick.  At the moment all the zones and the DHW look good and the TRV sensors are slowly repopulating so I'll leave `Use SQLite MessageIndex` enabled and monitor things for the next 24 hours.

**Comment by peternash** [comment]
@silverailscolo - after running for an hour or so it's apparent that the `current temperature` and `setpoint` values for most of my zone climate devices are not updating (comparing values with the Honeywell Total Connect Comfort cloud integration with Evohome).  Only 2 of the 12 zones are reflecting the changes in temperature and setpoint.  The DHW device seems to be updating correctly.  I've tried rebooting but that didn't help.  I've attached the most recent debug log but will turn `Use SQLite MessageIndex` back off for now.

[home-assistant_ramses_cc_2025-12-06T17-33-28.654Z.log](https://github.com/user-attachments/files/23990948/home-assistant_ramses_cc_2025-12-06T17-33-28.654Z.log)

**Comment by peternash** [comment]
@silverailscolo - I've done some further testing with 0.52.4 and the `Use SQLite MessageIndex` option enabled. It looks like the `setpoint` for all my climate zones is updating but the `current temperature` is not, except for two zones which are updating correctly.  I've looked at my Evohome configuration and those are the only two zones that are set as "multi-room zones" in Evohome.  As an experiment I tried changing another zone which has multiple TRVs from "single room zone" to "multi-zone room" and the current temperature started updating on that zone too.  I can't offer any insight into why that would be but with regard to the logs above the two multi-room zones are represented in HA as entities `climate.01_216136_02` (Hall) and `climate.01_216136_07` (Bathrooms).  The DHW control seems to be updating correctly and all the TRV and Thermostat sensors like temperature, heat demand, battery level etc. seem to be updating OK.

**Comment by peternash** [comment]
"Hall" is a multi-room zone and is showing current temperature, the other zones shown here are single room zones and current temperature is not available.  The setpoint and heating status appear to be updating correctly for all zones.

<img width="494" height="247" alt="Image" src="https://github.com/user-attachments/assets/1ce47652-1a8a-4208-9b6c-1b9328281f72" />

**Comment by Tchirana** [comment]
@peternash those multi room zones. What devices do you have in one of those rooms?

**Comment by silverailscolo** [comment]
So it seems that the (non-multi) Zones fail to get their "temperature" attribute from `Code._30C9':
(ramses_rf/system/zones.py line 737):
```
def temperature(self) -> float | None:  # 30C9
   return self._msg_value(Code._30C9, key=SZ_TEMPERATURE)  # type: ignore[no-any-return]
```

**Comment by silverailscolo** [comment]
@peternash 
Your logs contain a couple of these:
```
[ramses_rf.entity_base] No msg found for hdr 000A|RP|01:216136|07, tesk code 000A
```
I have a fix for that (and a spelling fix for 'task code' ;-) in a branch which you can set as a requirement in `manifest.json`:
`"ramses_rf@git+https://github.com/silverailscolo/ramses_rf.git@eb-sql-multizone-pnash"`

Can you try that?
I would also appreciate if you can add a ramses packetlog for the same period as your system log.

**Comment by peternash** [comment]
@Tchirana and @silverailscolo - here's an annotated copy of my `working_schema` where I've added the device types:

```
id: "01:216136"
working_schema:
  system:
    appliance_control: "10:064873" #R8810A OTH interface
  orphans: []
  stored_hotwater:
    sensor: "07:050121" #DHW sensor
    hotwater_valve: "13:042605" #BDR91 DHW relay
    heating_valve: null
  underfloor_heating: {}
  zones:
    "00":
      _name: Garden room
      class: radiator_valve
      sensor: "04:056673" #HR92 TRV
      actuators:
        - "04:034720" #HR91 TRV
        - "04:056673" #HR92 TRV
    "01":
      _name: Kitchen
      class: radiator_valve
      sensor: "22:012299" #DT4R thermostat
      actuators:
        - "04:034682" #HR91 TRV
    "02":
      _name: Hall #Multi-room zone
      class: radiator_valve
      sensor: "04:034716" #HR91 TRV
      actuators:
        - "04:034716" #HR91 TRV
        - "04:034726" #HR91 TRV
    "03":
      _name: Lounge
      class: radiator_valve
      sensor: "34:058721" #Y87RF round thermostat
      actuators:
        - "04:056679" #HR92 TRV
        - "04:219929" #HR92 TRV
    "04":
      _name: Dining room
      class: radiator_valve
      sensor: "04:056677" #HR92 TRV
      actuators:
        - "04:056677" #HR92 TRV
    "05":
      _name: Office
      class: radiator_valve
      sensor: "04:106557" #HR92 TRV
      actuators:
        - "04:106557" #HR92 TRV
    "06":
      _name: Master bed
      class: radiator_valve
      sensor: "04:056675" #HR92 TRV
      actuators:
        - "04:056675" #HR92 TRV
    "07":
      _name: Bathrooms #Multi-room zone
      class: radiator_valve
      sensor: "04:036066" #HR91 TRV
      actuators:
        - "04:034690" #HR91 TRV
        - "04:034722" #HR91 TRV
        - "04:036066" #HR91 TRV
        - "04:036068" #HR91 TRV
    "08":
      _name: Bedroom 2
      class: radiator_valve
      sensor: "04:208998" #HR92 TRV
      actuators:
        - "04:208998" #HR92 TRV
    "09":
      _name: Bedroom 3
      class: radiator_valve
      sensor: "04:208990" #HR92 TRV
      actuators:
        - "04:208990" #HR92 TRV
    0A:
      _name: Bedroom 4
      class: radiator_valve
      sensor: "04:208994" #HR92 TRV
      actuators:
        - "04:208994" #HR92 TRV
    0B:
      _name: Bedroom 5 #Test multi-room zone
      class: radiator_valve
      sensor: "04:208992" #HR92 TRV
      actuators:
        - "04:034684" #HR91 TRV
        - "04:034692" #HR91 TRV
        - "04:208992" #HR92 TRV
device_class: problem
friendly_name: Evohome controller System status
```

**Comment by peternash** [comment]
@silverailscolo - I've made that change to `manifest.json` and restarted.  So far it's the same behaviour as before, the current temperature is only updating for the multi-room zones.  If I clear the cache I get an initial, correct current temperature for _all_ zones but after that only the multi-room zones get updated values.  I'll leave it running but here are the logs so far:

[home-assistant_ramses_cc_2025-12-08T13-28-26.215Z.log](https://github.com/user-attachments/files/24033162/home-assistant_ramses_cc_2025-12-08T13-28-26.215Z.log)

[ramses_packets.log](https://github.com/user-attachments/files/24033164/ramses_packets.log)

**Comment by silverailscolo** [comment]
@peternash I've added a step to fetch the temp from a zone's sensor in the same branch/PR

**Comment by Tchirana** [comment]
@peternash I have never seen this before:
```
    "07":
      _name: Bathrooms #Multi-room zone
      class: radiator_valve
      sensor: "04:036066" #HR91 TRV
      actuators:
        - "04:034690" #HR91 TRV
        - "04:034722" #HR91 TRV
        - "04:036066" #HR91 TRV
        - "04:036068" #HR91 TRV
```

You have 4 rads in the same room or they are in fact more rooms?

**Comment by peternash** [comment]
@Tchirana - they are, in fact, four towel rails (or towel warmers) in three different bathrooms, hence the multi-room zone.  That's really the scenario the multi-room zone is intended for in Evohome.  It's a group of TRVs that can be scheduled and controlled collectively but each TRV uses it's own integral temperature sensor to set it's valve position to achieve the setpoint.  The setpoint is common for all the TRVs in the zone.  The representative temperature sensor for a multi-room zone is arbitary - it's just used for displaying the "zone temperature" which actually the temperature in just one of the rooms.  My "Hall" zone is set up that way because it actually consists of a TRV in the hall and another on the landing (1st floor) - the heat demands are quite different so it makes sense for each valve to adjust it's own heat demand.  To some extent it's a result of the 12 zone limit in Evohome - you have to make some compromises if you hit the 12 zone limit.

**Comment by peternash** [comment]
@Tchirana - this is what `heat_demand` and `temperature` sensors look like for the 4 TRVs in the "Bathrooms" zone.  You can see how the `heat_demand` and therefore valve position varies independently for each TRV even though their setpoints are always the same.  For my "single room zones" with multiple TRVs the `heat_demand` for the TRVs in the zone is always in lockstep.

<img width="500" height="656" alt="Image" src="https://github.com/user-attachments/assets/9b9e6bb9-10dd-4239-9951-f6dd59c7829d" />

**Comment by peternash** [comment]
@silverailscolo - I've rebooted to use the latest version from the branch and that looks promising.  Only about 20 minutes of data so far but I can see that `current_temperature` is changing for at least some of the "single room" zones.  It's probably updating on all of them but I need to wait for all the zone temperatures to change enough to confirm.  I'll leave it for an hour or two and check again.

**Comment by peternash** [comment]
@silverailscolo - the `current_temperature` on the "multi-room" zones is still updating OK.  On the other zones the temperature updated normally for about an hour after restarting, then the temperatures "froze" with no updates for about 90 minutes and then an isolated single update to all zones at about the same time.  I bit inconsistent so I'll keep gathering data including a debug log.

**Comment by silverailscolo** [comment]
The update of all zones might have been the result of a reloading/discovery of ramses_rf, just like you reported at startup.
I have to refine the temperature lookup to pass on the most recent value reported, not just checking for None.

**Comment by silverailscolo** [comment]
@peternash Added a new custom query for the latest temp value of either the zone or its sensor. Let's see

**Comment by peternash** [comment]
@silverailscolo - with the most recent patch from yesterday it seems very close.  Everything looked fine for several hours but overnight all but one climate zone became `unavailable` although the `history_graph` cards for all those climate entities were still tracking setpoint, temperature and heating status - don't really understand that one.  I cleared the cache and things looked OK for about 5 hours.  I just noticed that one single room zone did not reflect a scheduled update to it's setpoint in either the climate control or the `history_graph`. However, manually changing that setpoint again via the Evohome app caused it to be updated in HA. It looks like there may still be the potential for some data to be lost occasionally.  I'll keep monitoring.

**Comment by peternash** [comment]
@silverailscolo - again, after about 5 hours of running 6 of the 12 climate controls had gone `unavailable`.  The `current_temperature` on the `history_graph` cards was still updating for all zones but `setpoint` was not consistently updating.  A restart did not bring back the climate controls but clearing the caches did.  I'll leave it running until I see those symptoms again and then upload the debug log starting from the cache clearing.

**Comment by silverailscolo** [comment]
Thanks for your report. If you get a chance, please note the time that sensors "go flat" so that I can match that to the logs.

It might be we run into some limit to the database/memory or the log rollover without properly shutting down the MessageIndex database.

**Comment by peternash** [comment]
@silverailscolo - overnight all the climate entities for the zones went `unavailable`.  I've attached a debug log that covers this period.  I've also added a screenshot from the Activity log showing what times the devices went `unavailable`.  The DHW control and the device for the Evohome controller itself remained `available` throughout.  As far as I can see the history cards showing setpoint and current_temperature have been updating normally. Interestingly, there were scheduled changes in setpoint this morning but they had no impact on the state of the climate devices. However, a manual change to the Office setpoint at around 08:37 caused that climate device to become available again.  That change was made via Alexa and the Honeywell-Alexa integration, not via HA.  I don't know if it's significant that the scheduled change to the Office setpoint at 08:00 didn't cause the climate device to become available again, but the change made via Honeywell-Alexa at 08:37 did?

[home-assistant_ramses_cc_2025-12-10T08-51-56.405Z.log](https://github.com/user-attachments/files/24073754/home-assistant_ramses_cc_2025-12-10T08-51-56.405Z.log)

[ramses_packets.log](https://github.com/user-attachments/files/24073759/ramses_packets.log)

<img width="506" height="456" alt="Image" src="https://github.com/user-attachments/assets/2746f296-d198-47d8-85b3-0cb85e9b5266" />

<img width="1743" height="1080" alt="Image" src="https://github.com/user-attachments/assets/3e2c5c10-b889-41c1-8007-b192a7b95dfd" />

<img width="518" height="293" alt="Image" src="https://github.com/user-attachments/assets/cce23dff-14ee-430b-8223-5909e11356b2" />

<img width="1432" height="903" alt="Image" src="https://github.com/user-attachments/assets/0f142fc8-4b9c-428d-a236-ec40f84b3e7b" />

**Comment by peternash** [comment]
@silverailscolo - just confirmed that making a setpoint change via the Honeywell app causes the climate device for a zone to become `available` again.  I changed the Kitchen setpoint via the Honeywell app and the Kitchen climate device became `available` a few seconds later at 09:34:08 - I've attached a log fragment for for that period.

[home-assistant_ramses_cc_2025-12-10T09-34-29.672Z.log](https://github.com/user-attachments/files/24074180/home-assistant_ramses_cc_2025-12-10T09-34-29.672Z.log)

**Comment by silverailscolo** [comment]
@peternash thanks
`01:08:08` seems to be just after the MessageIndex 14h cleanup routine. The routine logs a missing `ts` (timestamp) at `01:06:07`.
I will focus on that process and compare your logs with my own hvac setup.
It definitely deserves a special test.

The reason external commands activate a sensor _might_ be that Ramses RF ignores any unknown entities and won't RQ them for an update. Will study your logs to confirm that too.

Feel free to turn off the SQL switch for now and cosy up.

**Comment by peternash** [comment]
@silverailscolo - also just confirmed that making a change to an `unavailable` climate device in the HA UI causes it to become `available` again. It's usable as is so I'll leave for a while and see if there's a consistent delay before devices go `unavailable` again - might provide a clue. Let me know when you need any further testing.

**Comment by silverailscolo** [comment]
The tweaks are now in master and I moved this job to a fresh branch, so you better update the requirement in `manifest.json` to:
`"ramses_rf@git+https://github.com/silverailscolo/ramses_rf.git@eb-sql-maintainloop"`

**Comment by silverailscolo** [comment]
@peternash Current master contains PR #365 with a fix for the periodic 'unavailable' effect. Can you try it out for your setup by updating the requirement in `manifest.json` to:
`"ramses_rf@git+https://github.com/ramses-rf/ramses_rf.git@master"`

**Comment by peternash** [comment]
@silverailscolo - looks like the integration won't start with the current master:

```
2025-12-18 16:29:26.561 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entity binary_sensor.18_072981_status for domain binary_sensor with platform ramses_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1380, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1024, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1149, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1090, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ramses_cc/binary_sensor.py", line 193, in extra_state_attributes
    SZ_KNOWN_LIST: [{k: shrink(v)} for k, v in gwy.known_list.items()],
                                               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/gateway.py", line 485, in known_list
    d.id: {k: d.traits[k] for k in (SZ_CLASS, SZ_ALIAS, SZ_FAKED)}  # type: ignore[misc]
              ^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/device/heat.py", line 1155, in traits
    "opentherm_traits": self.supported_cmds_ot,
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/entity_base.py", line 923, in supported_cmds_ot
    for msg_id in sorted(res)
                  ~~~~~~^^^^^
TypeError: '<' not supported between instances of 'str' and 'NoneType'
2025-12-18 16:29:27.323 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry RAMSES RF for ramses_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ramses_cc/__init__.py", line 169, in async_setup_entry
    await broker.async_start()
  File "/config/custom_components/ramses_cc/broker.py", line 211, in async_start
    await self.async_update()
  File "/config/custom_components/ramses_cc/broker.py", line 712, in async_update
    await self.async_save_client_state()
  File "/config/custom_components/ramses_cc/broker.py", line 271, in async_save_client_state
    schema, packets = self.client.get_state()
                      ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/gateway.py", line 265, in get_state
    if wanted_msg(msg, include_expired=include_expired)
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/gateway.py", line 251, in wanted_msg
    if msg._expired and not include_expired:
       ^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/message.py", line 350, in _expired
    self._fraction_expired = fraction_expired(self._pkt._lifespan)
                             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/message.py", line 327, in fraction_expired
    return (self._gwy._dt_now() - self.dtm - _TD_SECS_003) / lifespan
            ^^^^^^^^^
AttributeError: 'Message' object has no attribute '_gwy'
```

**Comment by silverailscolo** [comment]
Sorry to hear that. Can't find any recent changes to that `message.py` line. I'll create a new ramses _rf release so we can check that with current ramses_cc.

**Comment by peternash** [comment]
@silverailscolo - just to clarify, I only see those errors with the current master if `Use SQLite MessageIndex` is enabled.

**Comment by silverailscolo** [comment]
@peternash Do you see better results with the latest HACS update to Ramses RF 0.52.5?

**Comment by peternash** [comment]
@silverailscolo - I’ve been running 0.52.5 since last night with ‘Use SQLite MessageIndex’ enabled and all looks good so far. I’ll keep monitoring.

**Comment by silverailscolo** [comment]
Great. Let's close this issue and - when required - feel free to start a new one.
@peternash Thanks for your contribution in testing out our integration.

**Comment by peternash** [comment]
@silverailscolo - sorry to report that after several hours the climate devices for all the heating zones have gone `unavailable` again - similar behaviour to before. Don't know whether you want a separate issue or to reopen this one?

**Comment by silverailscolo** [comment]
Will reopen this one.

@PWhite-Eng Would you have an opportunity to compare your own results with what @peternash reports above?

**Comment by PWhite-Eng** [comment]
@silverailscolo, my HA setup is in no state to compare results right now, but once I’ve finished working on my little project, I’ll have a look at this.

**Comment by silverailscolo** [comment]
@peternash PR #382 fixes the above startup error
```
AttributeError: 'Message' object has no attribute '_gwy'
```
Sorry, not included in Release 0.53.0 so please try with Use SQLite MessageIndex option by setting current master as dependency in the usual way.

**Comment by peternash** [comment]
@silverailscolo - I've run a couple of extended tests with current master as a dependency.  When switching to `Use SQLite MessageIndex` without a restart I appear to get normal updates to zone setpoints and temperatures and the Zone devices remain available (2 x 24 hour tests).  However, if I restart HA I then lose the "friendly names" for the heating zones - i.e. the "Kitchen" device becomes "RAD 01:216136_01" in HA. The names don't seem to recover their "friendly" form.  The first log attached is a restart with debug logging enabled.

[home-assistant_ramses_cc_2026-01-09T09-40-22.800Z.log](https://github.com/user-attachments/files/24524449/home-assistant_ramses_cc_2026-01-09T09-40-22.800Z.log)

I've also noticed that if I clear the caches then the integration won't restart and raises an error (second attached log).  After clearing the caches the only way to get the integration to restart is by disabling `Use SQLite MessageIndex`

[home-assistant_ramses_cc_2026-01-09T09-43-42.093Z.log](https://github.com/user-attachments/files/24524452/home-assistant_ramses_cc_2026-01-09T09-43-42.093Z.log)

**Comment by silverailscolo** [comment]
This is the first fatal error:
```
2026-01-09 09:43:17.322 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry RAMSES RF for ramses_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 762, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ramses_cc/__init__.py", line 178, in async_setup_entry
    await broker.async_start()
  File "/config/custom_components/ramses_cc/broker.py", line 212, in async_start
    await self.async_update()
  File "/config/custom_components/ramses_cc/broker.py", line 720, in async_update
    await self.async_save_client_state()
  File "/config/custom_components/ramses_cc/broker.py", line 272, in async_save_client_state
    schema, packets = self.client.get_state()
                      ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/gateway.py", line 341, in get_state
    if wanted_msg(msg, include_expired=include_expired)
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_rf/gateway.py", line 327, in wanted_msg
    if msg._expired and not include_expired:
       ^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/message.py", line 363, in _expired
    self._fraction_expired = fraction_expired(self._pkt._lifespan)
                             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/ramses_tx/message.py", line 338, in fraction_expired
    if self._gwy:  # TODO self._gwy is never set !
       ^^^^^^^^^
AttributeError: 'Message' object has no attribute '_gwy'
```
Apparently not caught by PR #382 . Fixed in PR #387

**Comment by silverailscolo** [comment]
@peternash I've improved my "fix".
Can you reload master and check restart with `Use SQLite MessageIndex` On?

**Comment by peternash** [comment]
@silverailscolo - I'm testing with the current master and `Use SQLite MessageIndex`.  This seems more stable although there are still a couple of issues.

HA restarts are now OK with `Use SQLite MessageIndex` on.

At midnight an error was logged - presumably to do with housekeeping of some sort - see attached.

[Midnight.log](https://github.com/user-attachments/files/24541812/Midnight.log)

Clearing the cache raises an error but the integration continues to run - see attached.

[Clear cache.log](https://github.com/user-attachments/files/24541813/Clear.cache.log)

One zone (only) has persistently shown as `unknown` since clearing the cache but the others look OK - all the zone names are correct including the one with `unknown` status.

The Override state of the zones does not seem to be updating to reflect `None`, `Permanent` or `Temporary`.

Changing a zone temperature in the UI results in a `Temporary` override in Evohome as expected but HA shows it as `Permanent` in the UI.  Trying to change the Preset mode to `Permanent` via the UI results in an error (see attached).

[Preset mode.log](https://github.com/user-attachments/files/24541814/Preset.mode.log)

I'll carry on testing to see if anything else shows up.

**Comment by peternash** [comment]
Additional notes:

Selecting `Preset none` in the UI "woke up" the zone that was showing `unknown` status.  Setting `Preset none` via the UI works OK but trying to set either `Preset temporary` or `Preset permanent` results in an error as detailed above:

```
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 281473465389088 and this is thread id 281473063575752.
```

**Comment by silverailscolo** [comment]
> Setting `Preset none` via the UI works OK but trying to set either `Preset temporary` or `Preset permanent` results in an error as detailed above:

@peternash I've created a separate issue #395 for this item, and copied the log file.

**Comment by silverailscolo** [comment]
> Clearing the cache raises an error but the integration continues to run - see attached.

This error now has its own Issue #396 

The blocking call error is a known issue, see [ramses_cc issue 293](https://github.com/ramses-rf/ramses_cc/issues/293)

**Comment by peternash** [comment]
@silverailscolo - FYI, still running with `Use SQLite MessageIndex` and ramses_rf master as a dependency. Overnight all the Evohome zones went to `unknown` status again.  After an HA restart I've now lost all the zone names - all just showing names in the form RAD 01:216136_xx.  I'm aware there's a lot of activity on Ramses_rf so it's a bit of a moving target - I'm restarting HA daily to pick up the latest ramses_rf.  I'll leave the system running with the current master overnight to see if there's a correlation between the absent zone names and the tendency for zone status to go `unknown` after several hours.

**Comment by silverailscolo** [comment]
@peternash Could you install the upcoming integration release 0.53.1 from HACS so that we have a fresh system? That will set the dependency to "ramses-rf==0.53.1" but also update ramses_cc with some new stuff.

If that still hides the Zone names, I will rollback my recent change to _leave out the `3220` sim packet_ and you can edit the dependency as you have it set now, to `ramses_rf@master`.

**Comment by peternash** [comment]
@silverailscolo - Observations so far on integration 0.53.1 with `Use SQLite MessageIndex` on and the modified climate.py from [PR 408](https://github.com/ramses-rf/ramses_cc/issues/408).

Zone names appear to be updated correctly.

Clearing the cache no longer raises an error and the zone devices become available again within a minute or two with the correct zone names.

UI changes to the zone temperature appear to create the correct overrides without error

After several hours (9 hours on the last test) the heating zones go to `unknown` status.  Any change to the zone either via the HA UI or Honeywell system appears to bring the zone status back.

I've noticed that the DHW control `mode` is not being updated in the UI.  i.e. switching the DHW to on/off/auto mode does not update the displayed mode in the HA UI although it does correctly set the mode in Evohome. I've confirmed that this is not an issue if `Use SQLite MessageIndex` is off. I've not specifically looked for this before and I don't normally change the DHW mode often so I can't say with confidence when this issue first arose.

**Comment by silverailscolo** [comment]
@peternash Thanks for the update. Seems were are slowly moving forward on this 'feature'.
Two more fixes for asynchronous service actions and DHW thread safety with msg_db were later merged into `ramses_cc`, specifically for `water_heater.py` and `climate.py`. You might want to copy both from current master to your `custom_components/ramses_cc/` folder.

**Comment by peternash** [comment]
@silverailscolo - I've run a few 24+ hour tests with integration 0.53.1 but with the latest `climate.py` and `water_heater.py` from master (modified 12/01/26) and `Use SQLite MessageIndex` enabled. I've seen consistent results which can be summarised as follows:

After enabling `Use SQLite MessageIndex` the DHW mode stops updating in the UI 

Immediately after enabling `Use SQLite MessageIndex` the heating zone names and states display correctly.
After restarting HA the zone names and states continue to display correctly.
After clearing the caches the zone names and states refresh correctly after about a minute

The zone states continue to display correctly for several hours and restarting HA during this period has no negative impact on the zone names or states.

After about 8 or 9 hours the state of all the heating zones goes `unknown` at the same time but the zone names remain correct.

Restarting HA after this point does not restore the zone states which remain `unknown` but the zone names remain correct.  Making any change to a zone via the HA UI or Honeywell app will restore the state of that zone in HA.

From approx 24 hours after enabling `Use SQLite MessageIndex` any restart of HA will cause the zone names to revert to the `RAD 01:216136_XX` form instead of their "friendly names"

At this point clearing the "Discovered system schema" cache has no effect.  However, clearing the "System state cache" restores some, but not all of the zone friendly names and all of the zone states.

From this point onwards the only way to restore ALL the zone friendly names seems to be to turn off `Use SQLite MessageIndex`

I've repeated this 3 times and seen consistent results.  On the face of it there appear to be two different time based issues with the heating zones - the zone states going `unknown` after about 8 hours and the zone friendly names being lost after about 24 hours (although this only becomes apparent on a restart). It's hard to be precise about the timings but I've taken advantage of the house being unoccupied for a few days so there have been no other interactions with Evohome.  The heating zones were all on a constant permanent override during these tests.

**Comment by silverailscolo** [comment]
Thanks @peternash for your thorough report.

I expect the 24h pattern to be related to the SQLite maintenance loop. It _should_ report its activity in the system log, but haven't seen it in your previous logs.

After we fix a breaking bug in hvac fan_param with ramses_cc 0.53.2 I'll pick up evohome support.

**Comment by peternash** [comment]
@silverailscolo - I've been testing the `Use SQLite MessageIndex` option with the pre release 0.53.3 and 0.53.4.  I didn't see the zone states going `unknown` after 8 hours but only conducted one 24 hour test so not conclusive.  The other issues are unchanged.

However, I'd missed an issue in recent tests because I'd been focussing on the "state unknown" and zone names issues.  I can now see that when changing heating zone overrides or heating modes it takes a _very_ long time to update the HA UI to reflect that changes - in the order of 3-4 minutes or sometimes not at all.  I tracked back through previous versions (with `Use SQLite MessageIndex` enabled) and it looks like this was introduced in 0.53.1.  Going back to 0.52.5 I don't see this issue - zone updates are reflected in the HA UI in 2 or 3 seconds.  However, from 0.53.1 onwards I see the same delayed/inconsistent xone update behaviour in each release.  0.53.1 is also the release where the DHW mode stopped updating completely so I'm guessing that's the same cause.

This is all with `Use SQLite MessageIndex` `on` of course.

**Comment by silverailscolo** [comment]
> This is all with Use SQLite MessageIndex on of course.

@peternash Just a quick first check: Are these delays gone when you turn off the SQLite option?

**Comment by peternash** [comment]
@silverailscolo - yes, turning off `Use SQLite MessageIndex` restores normal behaviour, although -as reported- 0.53.3 and 0.53.4 (only) have introduced some delays of a much smaller magnitude [than] [issue #460](https://github.com/ramses-rf/ramses_cc/issues/460).  Those [long] delays are not apparent on 0.53.2 and are consistently around 30 seconds so something else going on there I think.

**Comment by PWhite-Eng** [comment]
According to my friend:

**Technical Analysis & Resolution Update**

Following a review of the threading architecture in recent releases, we have identified that the root cause of the `sqlite3.ProgrammingError` and associated test failures was a violation of SQLite's threading model. specifically, SQLite objects (connections/cursors) created in the main thread were effectively being blocked or accessed unsafely during heavy I/O operations, leading to the crashes observed.

**Resolution in 0.53.4:** The 0.53.4 release resolves this by strictly enforcing thread segregation for database operations:
- **Write Segregation:** All `INSERT` and `UPDATE` operations have been moved to a dedicated `StorageWorker` thread. The main event loop now offloads these tasks to a queue, preventing thread conflict.
- **Read Isolation:** The `MessageIndex` class (running on the main thread) now maintains its own independent read-only connection.
- **Concurrency:** We have enabled Write-Ahead Logging (`WAL`) mode by default. This ensures that the background writer thread does not lock the database file against readers on the main thread, preventing the "database locked" errors that were indirectly contributing to the test failures.

This architectural split ensures compliance with Python's `sqlite3` threading rules and should permanently resolve the reported `ProgrammingError`.

*Related: This fix also provides the foundation for resolving the UI latency reported in Issue ramses-rf/ramses_cc#460*

**Comment by PWhite-Eng** [comment]
**Update: Architecture Fix & Test Resolution**

We have successfully refactored the database layer to resolve both the threading crashes (this issue) and the performance latency (ramses-rf/ramses_cc#460).

**The Solution:** We have implemented a `StorageWorker` pattern.
- **Writes** are now offloaded to a background thread, completely removing blocking I/O from the main loop.
- **Reads** operate on a separate connection in `WAL` (Write-Ahead Logging) mode, ensuring they are never blocked by writes.
- **Thread Safety:** The write connection is owned exclusively by the worker thread, while the read connection is owned by the main thread. This strictly adheres to SQLite's threading model, eliminating the `ProgrammingError`.

**Test Suite Status:** The `test_systems.py` failures initially seen were caused by the test harness assuming synchronous (instant) DB writes.
- We have updated the test helpers (`load_test_gwy`) to account for the async nature of the new architecture.
- A special "Flush" mechanism has been added specifically for the test environment to guarantee data consistency during assertions.

All tests are now passing (Green). Hopefully! this fix is ready for the next release.

**Comment by silverailscolo** [comment]
@peternash You might test the`Use SQLite MessageIndex` option with current ramses_rf@master as dependency. It now includes PR #412

**Comment by peternash** [comment]
@silverailscolo - I've tested using ramses_rf@master as a dependency and I'm still seeing the same behaviour.  With `Use SQLite MessageIndex ON` updates to the climate entities are taking several minutes if at all.  With `Use SQLite MessageIndex OFF` updates are consistently taking about 40 seconds to display (although I think the recent change was only meant to address the SQLite issue anyway).  Just to make sure I opened a console to my HA container and confirmed that the copy of ramses_rf installed included the changes in PR [#412](https://github.com/ramses-rf/ramses_rf/pull/412)

**Comment by PWhite-Eng** [comment]
@peternash - thank you for your efforts in testing the new code, please keep up the good work, I am looking again at the issues you have very carefully logged and described.
Phil

**Comment by PWhite-Eng** [comment]
Dev discussion moved to Discussion https://github.com/ramses-rf/ramses_rf/discussions/191#discussioncomment-15594280

**Comment by peternash** [comment]
@silverailscolo - no change with 0.53.5 and `Use SQLite MessageIndex ON`.  Updates to climate entities are taking 3-5 minutes to appear in the UI.  I'd previously reported that the DHW entity was not updating at all but I now realise it was taking about 5 minutes and I was not waiting long enough to observe the change in the UI.

**Comment by silverailscolo** [comment]
@PWhite-Eng Short question: I plan to release 0.54.0 early tomorrow so we are ready for HA 2026.2.0.
Shall we approach improving SQLite as pre-releases after this "official" release?

**Comment by PWhite-Eng** [comment]
Hi @silverailscolo, releasing 0.54.0 on 4th February, and then dealing with  improving SQLite as pre-releases after this "official" release seems a very sensible way forward.

**Comment by silverailscolo** [comment]
@peternash Hi, could you try 0.55.5 with and without SQLite and report how it behaves on your setup?(regarding this issue 😃)

**Comment by peternash** [comment]
@silverailscolo - I've done some testing with 0.55.5, UseSQLiteMessageIndex `off` and have a few sensor issues - see [this comment](https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/4977).

I've done some limited testing with UseSQLiteMessageIndex `on` and saw the same issue of heating zones devices going `unavailable` after about 8 hours.

**Comment by silverailscolo** [comment]
@peternash Planning to release 0.56.0 _if_ your evohome systems are stable running current master.

We have developed a better understanding of the heat/OTB handling in ramses_rf. If you can confirm, I'll close this. To follow up on the SQLite MessageIndex we can start a fresh issue.

**Comment by peternash** [comment]
@silverailscolo - I'm still having a few issues with 0.55.8 - see [this comment](https://github.com/ramses-rf/ramses_cc/pull/570#issuecomment-4183061858)

However, with all the changes to fix climate entities going `Unknown` I thought I'd try 0.55.8 with `UseSQLiteMessageIndex` on the other Evohome system I look after.  That's a simpler configuration, no DHW controller and no OpenTherm bridge.  So far, after 12 hours that's looking pretty promising.  The climate entities have remained `known`. The only obvious issue I can see is that the `relay_demand` sensor on the BDR91 boiler control is showing `Unknown`.  It certainly looks like the recent changes have fixed some of the issues with UseSQLiteMessageIndex so happy to close this issue and revisit the SQLite option on my own system once we have a stable version.  At the moment the most recent version that works for me without _any_ issues is still 0.54.3 although we seem to be making progress.
